### ISSUE TITLE
"Show in sidepane" interferes with the MissingDrawer plugin

### ISSUE THREAD

**Issue by jacob-carlborg** [JulianEberius/Textmate-Minimap#31]
I have the MissingDrawer plugin installed and if I enable the "Show in sidepane" option the side pane from the missing drawer plugin gets a white background color instead of the default blue-like background color it should have (same as Finder).

**Comment by JulianEberius** [comment]
Hi again,

Yes, there are a lot of strange interactions between different TM plugins. This is due to the way these plugins work: there is no real Plugin API in TM, only Objective-C method swizzling. Also sometimes, (and I think this is the case here) two plugins load and/or swizzle the same classes. Basically there is no isolation between TM plugins. 

So, to make it short: I can't help at the moment with problems such as these (for the reasons mentioned in the other issues: There is Sublime Text 2, there will be TM2 at the end of the year, so this plugin is not supported anymore)

Sorry again,
Julian

**Comment by jacob-carlborg** [comment]
Ok, I see.
